In [1]:
import matplotlib.pyplot as plt # Para gráficar
import numpy as np # Para cálculos

# Paquete para la clase MOOP
from EMO.MOOP import MOOP

# Estrategia de reducción de objetivos 
# Deb & Saxena
from EMO.MOOP import Obj_NonRed
from EMO.MOOP import PCAs

# Para Brockhoff & Zitzler
from EMO.MOOP import MOSS_Exact # Computa el algoritmo exacto para el problema MOSS
from EMO.MOOP import Sets_Delta # Retorna los distintos subconjuntos de objetivos con sus errores asociados

In [7]:
# Se definen las funciones del MOOP que se quiere resolver
def f1(x):
    return 4*x[0]**2-4*x[0]+1

def f2(x):
    return x[0]**3

def f3(x):
    return -x[0]+1

def f4(x):
    x = x[0]
    if x >= 0 and x <= 0.25:
        return -4*x+1
    elif x > 0.25 and x <= 0.5:
        return 4*x-1
    elif x > 0.5 and x <= 0.75:
        return -4*x+3
    elif x > 0.75 and x <= 1:
        return 4*x-3

# Llamando a la clase MOOP
problem = MOOP(functions = [f1,f2,f3,f4], # Una lista con los nombres de las funciones
               num_variables = 1, # Número de variables de las funcione objetivos
               intervals = (0,1)) # Definición de intervalos de las variables de decisión

# Resolviendo el problema con NSGA - II
problem.solveNSGA2(num_generations = 20, # Número de generaciones
                   population_size = 100, # Número de individuos en la población (se mantiene estático en cada generación)
                   plot_iter = False) # Para imprimir la gráfica de las soluciones

In [8]:
# Esta función sirve para ver el PCA aplicado a las soluciones en el espacio objetivo
# En problem.eval se encuentran las evaluaciones de las soluciones (espacio objetivo)
PCAs(problem.eval)

(array([5.30808638e+00, 1.47498706e+00, 2.30107084e-01, 3.55811781e-06]),
 array([[ 0.46390117,  0.46963599, -0.70168524,  0.26809617],
        [ 0.63139907, -0.25658246, -0.03359611, -0.7310075 ],
        [-0.53261416,  0.50971463, -0.25069735, -0.62742648],
        [ 0.32008292,  0.67364566,  0.66607804,  0.00940724]]),
 array([ 75.687253  ,  96.7188849 ,  99.99994927, 100.        ]),
 array([[ 1.        ,  0.53942831, -0.19446416,  0.50213566],
        [ 0.53942831,  1.        , -0.92872326,  0.24495726],
        [-0.19446416, -0.92872326,  1.        , -0.05587181],
        [ 0.50213566,  0.24495726, -0.05587181,  1.        ]]))

In [9]:
functions = ['f1', 'f2', 'f3', 'f4'] # Se define una lista donde las funciones se pasan como "strings"

# El siguiente código aplica la estrategia de Deb & Saxena a las soluciones en el espacio objetivo
# Se ha elegido un umbral de corte del 98%
Obj_NonRed(problem.eval, functions, 98)

{'f2', 'f3', 'f4'}

In [10]:
# Se aplica el algoritmo exacto de la estrategia de 
# Brockhoff & Zitzler a la población de problem.eval
MOSS_Exact(problem.eval, functions)

[['f2', 'f3']]

In [11]:
# Genera los subconjuntos de objetivos, con el error máximo respectivo
Sets_Delta(problem.eval, functions)

0 ['f1', 'f2', 'f3', 'f4']
0 ['f1', 'f2', 'f3']
1.0 ['f1', 'f2', 'f4']
1.0 ['f1', 'f3', 'f4']
0 ['f2', 'f3', 'f4']
1.0 ['f1', 'f2']
1.0 ['f1', 'f3']
0.9999942781090352 ['f1', 'f4']
0 ['f2', 'f3']
1.0 ['f2', 'f4']
1.0 ['f3', 'f4']
0.9999942781090352 ['f1']
1.0 ['f2']
1.0 ['f3']
0.9998724551155673 ['f4']
