In [1]:
import inspyred
import matplotlib.pyplot as plt
import numpy as np

#Paquetes a usar para los MOOP
from EMO.MOOP import MOOP
from EMO.MOOP import Obj_NonRed
from EMO.MOOP import PCAs

# Para Brokhoff & Zitzler
from EMO.MOOP import MOSS_Exact
from EMO.MOOP import performExactAlgorithm
from EMO.MOOP import Sets_Delta

In [7]:
def f1(x):
    return 1 - np.exp(-np.sum((x-1/np.sqrt(len(x)))**2))

def f2(x):
    return 3*f1(x)

def f3(x):
    return 2*f1(x)

def f4(x):
    return 5*f1(x)

def f5(x):
    return f3(x)+f4(x)


problemEj3 = MOOP(seed = 100,functions = [f1,f2,f3,f4,f5], num_variables = 3, intervals = (-4,4))
problemEj3.solveNSGA2(num_generations = 100, population_size = 100, plot_iter = False)#'last')

In [8]:
PCAs(problemEj3.eval)

(array([ 2.50000000e+01,  3.94306379e-31,  2.58926434e-33,  0.00000000e+00,
        -7.40148683e-16]),
 array([[-0.4472136 , -0.37080945, -0.89349044, -0.89442719,  0.2236068 ],
        [-0.4472136 ,  0.72905581,  0.22478718,  0.2236068 ,  0.2236068 ],
        [-0.4472136 , -0.23605021,  0.25475246,  0.2236068 ,  0.2236068 ],
        [-0.4472136 ,  0.30482018,  0.22384413,  0.2236068 , -0.89442719],
        [-0.4472136 , -0.42701632,  0.19010666,  0.2236068 ,  0.2236068 ]]),
 array([100., 100., 100., 100., 100.]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [9]:
functions = ['f1', 'f2', 'f3', 'f4', 'f5']
Obj_NonRed(problemEj3.eval, functions, 95)

{'f1'}

In [15]:
MOSS_Exact(problemEj3.eval, functions,100)

[['f1'], ['f2'], ['f3'], ['f4'], ['f5']]

In [12]:
Sets_Delta(problemEj3.eval,functions)

1.065067799510544e-07 ['f1', 'f2', 'f3', 'f4', 'f5']
7.607627139361028e-08 ['f1', 'f2', 'f3', 'f4']
1.065067799510544e-07 ['f1', 'f2', 'f3', 'f5']
1.065067799510544e-07 ['f1', 'f2', 'f4', 'f5']
1.065067799510544e-07 ['f1', 'f3', 'f4', 'f5']
1.065067799510544e-07 ['f2', 'f3', 'f4', 'f5']
4.564576283616617e-08 ['f1', 'f2', 'f3']
7.607627139361028e-08 ['f1', 'f2', 'f4']
1.065067799510544e-07 ['f1', 'f2', 'f5']
7.607627139361028e-08 ['f1', 'f3', 'f4']
1.065067799510544e-07 ['f1', 'f3', 'f5']
1.065067799510544e-07 ['f1', 'f4', 'f5']
7.607627139361028e-08 ['f2', 'f3', 'f4']
1.065067799510544e-07 ['f2', 'f3', 'f5']
1.065067799510544e-07 ['f2', 'f4', 'f5']
1.065067799510544e-07 ['f3', 'f4', 'f5']
4.564576283616617e-08 ['f1', 'f2']
3.0430508557444114e-08 ['f1', 'f3']
7.607627139361028e-08 ['f1', 'f4']
1.065067799510544e-07 ['f1', 'f5']
4.564576283616617e-08 ['f2', 'f3']
7.607627139361028e-08 ['f2', 'f4']
1.065067799510544e-07 ['f2', 'f5']
7.607627139361028e-08 ['f3', 'f4']
1.065067799510544e-07